### ISSUE TITLE
Issue with moment in .csv with /PROP/SPR_BEAM

### ISSUE THREAD

**Issue by SonSiont** [OpenRadioss/OpenRadioss#1625] opened 2023-06-23 08:15 UTC
**Describe the bug**
A spring with the property SPR_BEAM does not report the moment in ...T01.csv, but the derivation of it. 

**To Reproduce**
Run the attached Radioss model and convert to csv.

**Expected behavior**
The .csv file should have the moment.

**Output**
The archive with the input:
[model.tar.gz](https://github.com/OpenRadioss/OpenRadioss/files/11846209/model.tar.gz)
The model:
![dispX](https://github.com/OpenRadioss/OpenRadioss/assets/80820850/b6466eb4-02b6-433c-b639-86befbc8b480)
The reported MY: 
![t1](https://github.com/OpenRadioss/OpenRadioss/assets/80820850/7c9a520e-7997-42a7-8329-fd37674b9b13)

The integrated curve:
![integral](https://github.com/OpenRadioss/OpenRadioss/assets/80820850/a393f805-b1a3-4ced-899c-a24fbe5c3ef2)

**Desktop (please complete the following information):**
 - Version [93f8637214870e1ce15344339ee860f6356c469a]
- Hardware [Linux; Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (x86_64), 3499 MHz,  64217 MB RAM]
- Configuration [number of OpenMP threads, and MPI tasks]

**Additional context**

**Comment by PaulAltair** [comment] 2023-06-23 21:57
I am unable to replicate, running your model and converting to csv, I get the curve per your 'integrated' values directly:
plotted here in excel
![image](https://github.com/OpenRadioss/OpenRadioss/assets/98418895/99fdd3e7-ff4a-45cc-8083-5c505bf6ade9)
and hypergraph
![image](https://github.com/OpenRadioss/OpenRadioss/assets/98418895/f84d527a-8db6-4bcd-9d53-5fb84e32363d)
my run:
[model.zip](https://github.com/OpenRadioss/OpenRadioss/files/11853383/model.zip)

**Comment by PaulAltair** [comment] 2023-06-26 13:35
The one I shared was windows, but I ran in both Windows and Linux and the results were the same in both, not sure what the cause could be... Can you share your T01, we can see then if it is due to Radioss or the converter, I'm travelling today for the user meeting, but should be able to check this evening.

**Comment by SonSiont** [comment] 2023-06-26 13:45
Hi,
hier the T01:
[conradT01.gz](https://github.com/OpenRadioss/OpenRadioss/files/11869927/conradT01.gz).
You are on your way to the user meeting. I tried to get an invitation, but I didn't get a response. Are there so many users there?

**Comment by SonSiont** [comment] 2023-06-26 13:56
Hi,
it seems to be a RADIOSS issue, when I convert your T01 file I get the correct moment.

**Comment by SonSiont** [comment] 2023-06-26 15:06
Hi,
dropping /TH/TITLE from conrad_0001.rad, I lose the names, but the results are fine.

**Comment by PaulAltair** [comment] 2023-06-26 15:28
> Hi,
> hier the T01:
> [conradT01.gz](https://github.com/OpenRadioss/OpenRadioss/files/11869927/conradT01.gz).
> You are on your way to the user meeting. I tried to get an invitation, but I didn't get a response. Are there so many users there?
> 

Did you register? It is an open invite to all [User Day, you can join remotely, the event will be streamed Registration](https://web.altair.com/openradioss-users-day-2023)

**Comment by PaulAltair** [comment] 2023-06-26 16:42
> > Hi,
> > dropping /TH/TITLE from conrad_0001.rad, I lose the names, but the results are fine.
> 
> Ok, but I ran with no changes...

In fact, the raw data in the T01 is always impulse, the conversion to force/moment in CSV is dependent on the Content of the TITLE file when using the converter, so can you check, does your TITLE file match mine? Without /TH/TITLE I would expect you to get the impulse, rather than moment... i.e. the opposite of what is happening for you

**Comment by PaulAltair** [comment] 2023-06-27 05:36
> Hi,
> the conradT01_TITLES files differ in the EOL, after dos2unix of your file, both files are identical.
> Here are most files of a rerun.
> [rerun.tar.gz](https://github.com/OpenRadioss/OpenRadioss/files/11871919/rerun.tar.gz)
> 
> Regarding the user day: I made the registration without a response. The streaming is fine but I like to speak with some of the developers or speakers.

If your registration was received, you should have received a confirmation email and another this morning with stream information, if not, then maybe try again?

**Comment by elequiniou** [comment] 2023-08-18 09:44
Closed as not able to reproduce.

**Closed** 2023-08-18 09:44 UTC
