### ISSUE TITLE
The Itetra4 option in /PROP/SOLID seems ineffective when there are HEXA and TETRA4 elements in the same part

### ISSUE THREAD

**Issue by wgm096350** [OpenRadioss/OpenRadioss#1272] opened 2023-03-23 03:18 UTC
The part containing both HEXA and TETRA4 elements is shown below (a cube, half HEXA half TETRA4):
![image](https://user-images.githubusercontent.com/24369346/227091316-01bbabae-cd69-4761-ac2f-b40f960a9688.png)
In the kkkk_0000.rad file, Itetra4 could be set to all of the available values (0, 1, 3, 1000). However, in the kkkk_0000.out file which is generated by starter_win64.exe, the Itetra4 is set to 0 regardless of the value of Itetra4 in the kkkk_0000.rad file.
![image](https://user-images.githubusercontent.com/24369346/227093251-55487b37-0e5b-45c6-9bee-5ffad86f985b.png)

**Comment by wgm096350** [comment] 2023-03-23 03:22
[kkkk_0000.zip](https://github.com/OpenRadioss/OpenRadioss/files/11046611/kkkk_0000.zip)

**Comment by wgm096350** [comment] 2023-03-23 03:41
When there are only TETRA4 elements in the part, the value of Itretra4 in the *.rad file is respected. 
A question is: if both HEXA and TETRA4 elements are used in the same part, how to set the options of TETRA4 to the desired value?
![image](https://user-images.githubusercontent.com/24369346/227096031-e5564e0d-135e-4b45-a16a-37896f30f6b1.png)

**Comment by Schwoertzig** [comment] 2023-03-28 11:49
Hi @wgm096350 ,
Thank you for reporting this behavior. Unfortunately I was not able to reproduce.
I am running your test on linux64 with last commit 76294da49d3968ae84048d2bb67e44ad658411fd
Whatever it contains (hexa only, tetra only, mixed hexa+tetra), I always observe the same behavior :
1       -> 1
2       -> 2
3       -> 3
1000 -> 1000

We are going to test also on win64.

In addition to that, this test was the opportunity to introduce a check related to ITET4 value. I am going to display a warning message if ITET4 value is not relevant. Possible values are only {0,1,3,1000} .

Thanks & Best Regards

**Comment by laurent-altr** [comment] 2023-05-22 06:43
Hi @wgm096350, 
I believe the issue reported here has been successfully resolved with the recent updates. 
If the problem still persists, feel free to reopen this issue or create a new one.

Best regards

**Closed by laurent-altr** 2023-05-22 06:43 UTC
