### ISSUE TITLE
Law19 EREF sh3n element with initially tension works not corectly

### ISSUE THREAD

**Issue by Heguo-Ou** [OpenRadioss/OpenRadioss#1766] opened 2023-08-07 04:35 UTC
For a fvm airbag model, sh3n elements and law19 with element reference (/EREF). When sh3n elements were initially in tension (usually caused by folding airbag mesh with hand), then not only the starter reports WARNING ID 863, but also the shape of inflated airbag looks not smooth for those initial in tension elements.

The cfg of the /prop is ishell=4 ismstr=1 zerostress=1, and ishell=24 ismstr=11 zerostress=1 gives same issue. 

The other thing is: if the sh3n elements was initially in compression, there was not any issues as above.

**Comment by MarianBulla** [comment] 2023-08-07 06:31
Hello Heguo-Ou,
thank you very much for your interest in OpenRadioss and airbags.

In order to better reproduce your issue, can you add your model (or a smaller part of it), where I can try to reproduce your issue, please ?

Thanks and best regards,
Marian

**Comment by Heguo-Ou** [comment] 2023-12-22 06:38
ye...I'll try to send you the model, but I don't like to open it to public here
![20231222143340](https://github.com/OpenRadioss/OpenRadioss/assets/114550384/20523131-02ce-4338-bd64-a9bd4f7d8781)

**Comment by MarianBulla** [comment] 2024-01-16 12:04
Hi Hegue-Ou,

can you send me an e-mail to:  communitymanager@openradioss.org

Thanks and best regards,
Marian

**Comment by MarianBulla** [comment] 2024-03-28 15:49
Hi Hegue-Ou,

due to our exchange, I will close this ticket.

In case of any questions, feel free to contact me again :-)

Hope it is ok for you, anyway ?

Thanks and best regards,
Marian

**Closed by MarianBulla** 2024-03-28 15:49 UTC
