### ISSUE TITLE
Installation of openradioss using spack is failing

### ISSUE THREAD

**Issue by akamishra2826** [OpenRadioss/OpenRadioss#2367] opened 2024-02-23 11:58 UTC
**Describe the bug**
Installation of openradioss starter and engine using spack is failing 

**To Reproduce**
spack install openradioss-starter@main%gcc@13.1.0

**Expected behavior**
openradioss starter package should be installed

**Output**
![image](https://github.com/OpenRadioss/OpenRadioss/assets/131798033/face3785-f5a7-4b81-ade9-17e04633c176)

**Desktop (please complete the following information):**
 - Version [64c36b136f0baee6fcbb6f5315a3114a963ad1cb]
- Hardware [AMD zen4 ]

**Comment by OlivierWienholtz** [comment] 2024-02-26 10:36
Hello,

OpenRadioss can be compiled using DevToolset 13. We are testing gcc-13.1.1
Compilation using build_script.sh (Bash script) is working fine.

I have not tested Spack yet. I would need more insight how you are setting up Spac & the scripts to understand your problem.
From the error logs:

Line 231-235 is a post Build target to create an exec directory (if not exist) & copy the binary here in to make it available out of build directory

Line 238 : include list
target_include_directories(${EXEC_NAME} PRIVATE ${include_dir_list}  )
Finds all include directory of Starter project for build directory.

Hope it helps,
Olivier W.

**Comment by akamishra2826** [comment] 2024-02-26 10:55
@OlivierWienholtz , 

If you are familiar with spack then below steps will be easy to understand for how I setup spack and script to build openradioss starter.
[..]
-----------------------------------------------
setup spack and gcc compiler
-----------------------------------------------
$ git clone https://github.com/spack/spack.git
$ cd spack 
$ source  source share/spack/setup-env.sh 
$ spack install gcc@13.1.0
$ spack cd -i gcc
$ spack compiler add $PWD

-------------------------------------------------------
build recipe of openradioss-starter using spack
-------------------------------------------------------
$ spack install openradioss-starter@main%gcc@13.1.0

**Comment by schrummy14** [comment] 2024-03-20 15:17
Hello,
The issue isn't with openradioss but with the spack package file.
The DEXEC_NAME cmake variable is missing from the spack definition:
```bash
diff --git a/var/spack/repos/builtin/packages/openradioss-starter/package.py b/var/spack/repos/builtin/packages/openradioss-starter/package.py
index 36d6b8fc7c..4c6f570423 100644
--- a/var/spack/repos/builtin/packages/openradioss-starter/package.py
+++ b/var/spack/repos/builtin/packages/openradioss-starter/package.py
@@ -73,8 +73,10 @@ def cmake_args(self):
 
         if "+sp" in self.spec:
             args.append("-Dprecision=sp")
+            precisionToUse="_sp"
         else:
             args.append("-Dprecision=dp")
+            precisionToUse=""
 
         if "+debug" in self.spec:
             args.append("-Ddebug=1")
@@ -86,6 +88,7 @@ def cmake_args(self):
         else:
             args.append("-Dstatic_link=0")
 
+        args.append(f"-DEXEC_NAME=starter_linux{self.compiler_name}{precisionToUse}")
         return args
 
     def install(self, spec, prefix):
```

I tested this change on Rocky 9 with the latest spack-main, and it works to build the starter, but I got a different error when building the engine file. This is probably because I did not install gcc using spack and simply used the gcc provided by rocky linux.

**Comment by schrummy14** [comment] 2024-03-22 14:49
Hello,
Using spack to build packages is often an easy thing to do, but as of right now, the issue with building openradioss is still present.
https://github.com/spack/spack/issues/42866

The maintainer is working on it but could take some time.

As for how one would normally build with spack (good for debian and rhel, have not tried their windows version):

Download spack: `git clone -c feature.manyFiles=true https://github.com/spack/spack.git`
Source the environment: `source spack/share/spack/setup-env.sh`
Now install a package: `spack install openradioss-starter` (this may still error, I have not checked the main repo...)

This will build the openradioss-starter with default options and all dependencies:
```bash
[+]  openradioss-starter@main%gcc@13.2.1~debug~ipo~sp~static_link build_system=cmake build_type=Release generator=make arch=linux-fedora39-zen3
[+]      ^cmake@3.27.9%gcc@13.2.1~doc+ncurses+ownlibs build_system=generic build_type=Release arch=linux-fedora39-zen3
[+]          ^curl@8.6.0%gcc@13.2.1~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-fedora39-zen3
[+]              ^nghttp2@1.57.0%gcc@13.2.1 build_system=autotools arch=linux-fedora39-zen3
[+]          ^ncurses@6.4%gcc@13.2.1~symlinks+termlib abi=none build_system=autotools arch=linux-fedora39-zen3
[+]          ^zlib-ng@2.1.6%gcc@13.2.1+compat+new_strategies+opt build_system=autotools arch=linux-fedora39-zen3
[+]      ^gcc-runtime@13.2.1%gcc@13.2.1 build_system=generic arch=linux-fedora39-zen3
[+]      ^gmake@4.4.1%gcc@13.2.1~guile build_system=generic arch=linux-fedora39-zen3
[+]      ^perl@5.38.0%gcc@13.2.1+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1 arch=linux-fedora39-zen3
[+]          ^berkeley-db@18.1.40%gcc@13.2.1+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-fedora39-zen3
[+]          ^bzip2@1.0.8%gcc@13.2.1~debug~pic+shared build_system=generic arch=linux-fedora39-zen3
[+]              ^diffutils@3.10%gcc@13.2.1 build_system=autotools arch=linux-fedora39-zen3
[+]          ^gdbm@1.23%gcc@13.2.1 build_system=autotools arch=linux-fedora39-zen3
[+]      ^python@3.11.7%gcc@13.2.1+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=13fa8bf,b0615b2,ebdca64,f2fd060 arch=linux-fedora39-zen3
[+]          ^expat@2.6.2%gcc@13.2.1+libbsd build_system=autotools arch=linux-fedora39-zen3
[+]              ^libbsd@0.12.1%gcc@13.2.1 build_system=autotools arch=linux-fedora39-zen3
[+]                  ^libmd@1.0.4%gcc@13.2.1 build_system=autotools arch=linux-fedora39-zen3
[+]          ^gettext@0.22.4%gcc@13.2.1+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz build_system=autotools arch=linux-fedora39-zen3
[+]              ^libiconv@1.17%gcc@13.2.1 build_system=autotools libs=shared,static arch=linux-fedora39-zen3
[+]              ^libxml2@2.10.3%gcc@13.2.1+pic~python+shared build_system=autotools arch=linux-fedora39-zen3
[+]              ^tar@1.34%gcc@13.2.1 build_system=autotools zip=pigz arch=linux-fedora39-zen3
[+]                  ^pigz@2.8%gcc@13.2.1 build_system=makefile arch=linux-fedora39-zen3
[+]                  ^zstd@1.5.5%gcc@13.2.1+programs build_system=makefile compression=none libs=shared,static arch=linux-fedora39-zen3
[+]          ^libffi@3.4.4%gcc@13.2.1 build_system=autotools patches=070b1f3 arch=linux-fedora39-zen3
[+]          ^libxcrypt@4.4.35%gcc@13.2.1~obsolete_api build_system=autotools patches=4885da3 arch=linux-fedora39-zen3
[+]          ^openssl@3.2.1%gcc@13.2.1~docs+shared build_system=generic certs=mozilla arch=linux-fedora39-zen3
[+]              ^ca-certificates-mozilla@2023-05-30%gcc@13.2.1 build_system=generic arch=linux-fedora39-zen3
[+]          ^pkgconf@1.9.5%gcc@13.2.1 build_system=autotools arch=linux-fedora39-zen3
[+]          ^readline@8.2%gcc@13.2.1 build_system=autotools patches=bbf97f1 arch=linux-fedora39-zen3
[+]          ^sqlite@3.43.2%gcc@13.2.1+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-fedora39-zen3
[+]          ^util-linux-uuid@2.38.1%gcc@13.2.1 build_system=autotools arch=linux-fedora39-zen3
[+]          ^xz@5.4.6%gcc@13.2.1~pic build_system=autotools libs=shared,static arch=linux-fedora39-zen3
```

Since I have already built it, you will see the "[+]" characters instead of " - ".
You can see that it defaulted to using my linux box's built in gcc version, but as was mentioned above, you can install compilers and use those. So, if I wanted to use the aocc compiler, I would first need to install it and add it to the environment (see above messages), then call the installer as:
`spack install openradioss-starter%aocc`

Since all the apps are built and stored under the spack folder, you can easily delete everything. 

A difficulty that I can see in using spack is that OpenRadioss has a rolling window of releases.
Due to this, spack maintainers cannot point to a specific version of OpenRadioss, but instead, have to point to the main branch of your git repo.

**Comment by OlivierWienholtz** [comment] 2024-03-22 15:05
Thank You, 
I'll have a closer look.

**Comment by laurent-altr** [comment] 2024-03-29 11:50
Hello @akamishra2826 
It should be fixed now: https://github.com/spack/spack/pull/43365

**Closed** 2024-04-23 06:57 UTC
