### ISSUE TITLE
OpenRadioss does not converge with increasing spatial resolution for a cantilever beam simulation

### ISSUE THREAD

**Issue by Fonotec** [OpenRadioss/OpenRadioss#1758] opened 2023-08-03 09:27 UTC
**Describe the bug**
I constructed a set of rad files of a cantilever beam on which I impose a line force on the side that is not attached. The cantilever beam has a size of 40 mm x 10 mm x 2.5 mm and the imposed total force is expected to cause an average displacement of 0.78 mm. To test this I use a purely elastic material model (/MAT/LAW1) and shell elements. This test case I run for 6 different spatial resolutions, namely 5 mm, 2.5 mm, 1.25 mm, 0.625 mm, 0.3125 mm, 0.15625 mm). To run the model I use a CFL condition of 0.45 because I found that the model does not converge well for the default CFL condition of 0.9. I did not impose any damping such that we would expect a clear periodic oscillation. The result of running the model at different resolutions is the following:

[cantileverbeamtest_0_200_default.pdf](https://github.com/OpenRadioss/OpenRadioss/files/12248827/cantileverbeamtest_0_200_default.pdf)

One thing that is directly clear from this image is that the solution of the different resolutions does not converge properly. Firstly, 0.3125 mm quickly diverges and does not appear to realistic at all. The other solutions seem to be okayish converged in the initial 40 ms. But if we look a bit more closely in the first 100 ms we can already clearly see that the solution is decaying much quicker for the higher resolution. Both 0.15625mm and 0.625 mm clearly are losing amplitude and therefore are also losing energy. Also for 1.25 mm I can already see that the solution gets a smaller amplitude. Below I have a big plot (otherwise the lines cannot be seperated) with the different simulations and their corresponding energy components:

[energy_budget_resolution.pdf](https://github.com/OpenRadioss/OpenRadioss/files/12248938/energy_budget_resolution.pdf)

You see here that for some simulations the kinetic energy decreases and for some even the internal energy decreases. For the 0.15625 mm the internal energy gets very low. 

For the 1.25 mm I investigated how the convergence is with CFL condition and I found the solution is converged well for the CFL condition that I am using. Furthermore, I had a look at the convergence between different shell formulations at the highest resolution simulation and compared QEPH shell formulation (my default) with QBAT and Belytschko and find that those are even worse:

[cantileverbeamtest_0_200_shell.pdf](https://github.com/OpenRadioss/OpenRadioss/files/12249031/cantileverbeamtest_0_200_shell.pdf)

The question is how can we improve the numerical convergence of this simulation with resolution? Any suggestions are welcome! Let me know if you need more information.

**To Reproduce**
To reproduce this behaviour you can find the rad files at this link:
https://filesender.surf.nl/?s=download&token=7cd01cd2-f6f4-4ce7-b5c3-3e71f233a9d4

The starter returns 3 or 4 warnings but these are related to the time file and are not impacting the result. 

**Expected behavior**
I expect the solution to converge if I run simulations with higher spatial resolution, I expect the convergence towards a mean displacement of the theoretical static solution while the oscillation keeps having the same amplitude. But I find that this is not happening, OpenRadioss start to clearly not converge even for so few dynamical times as 200. We investigate this problem specifically because we know what the static solution is and what the natural frequencies would be.

**Output**
Explained in the description

**Desktop (please complete the following information):**
 - Version 9b676a81b8fb261ea5181f6a7838525393e49fa4
- Hardware: Intel(R) Xeon(R)
- Configuration: No MPI, 1 to 6 threads (4 and 6 threads for the higher resolution)

**Additional context**
None

**Comment by qiangRadioss** [comment] 2023-08-04 10:35
Hello Fonotec,

thanks for this interesting studies.
I guess the problem is that finer meshes excite higher frequency modes and need to be stabilized more numerically.
I think increasing dn (in /PROP/SHELL) with finer mesh could improve the convergence issues, you could take a trying.
Anyway, the default value of dn has not been designed for very finer mesh, i think it's even questionable for the modeling with shell element with high ratio of thickness/mesh_size (e.g. >10).
B.T.W. some of you rad files use npt=1 (at least in the file of 0.625mm) instead of npt=5 (or 0), npt=1 will have only membrane stiffness, i guess that's just a typo error.

hope this helps.

Qiang.

**Comment by Fonotec** [comment] 2023-08-04 14:07
Hello Qiang, 

Thanks for your reply! I will follow your suggestion and try slightly higher values of a factor 2, 4 and 8 for the shell numerical damping (dn). I guess this will indeed improve the numerical stability but I think this will not let the solution converge to the correct solution. I think it will cause the amplitude to be damped more, so the solution for different resolutions will not be converged, they will diverge a bit more. 

You have a valid point that the thickness/mesh_size might be a bit questionable for modeling with shell elements at the highest resolutions. Parallel to this I will investigate whether this indeed is causing problems. For this I propose that I will do a similar set of cantilever beam simulations over 2^6 orders of resolution but for which the thickness/mesh_size does not exceed a factor of a few at the highest resolution. 

Yes, indeed npt=1 is a typo in some rad files that was a parameter I changed in an other set of tests that I was performing. 

I will come back to you once I performed the tests. 

Regards,
Folkert

**Comment by Fonotec** [comment] 2023-08-08 14:22
Hello Qiang, 

I tried to use a larger dn to improve the convergence, I increased dn for my highest resolution simulation and find that this does not seem to influence the solution visibly. I tried besides the fiducial value of 0.015 (for QEPH shells) 3 values that are 2, 4 and 8 times larger. In the figure below you can see that the result is (almost) identical:

[cantileverbeamtest_100percent.pdf](https://github.com/OpenRadioss/OpenRadioss/files/12292317/cantileverbeamtest_100percent.pdf)

I double checked that the parameter indeed is read in correctly, I can see in the .out file that the value of dn is set to the value that I want. 

Regards,
Folkert

**Comment by qiangRadioss** [comment] 2023-08-09 08:09
Hi Folkert,

I've tested the case of 0.3125mm, i got the following :
![beam_0 3125](https://github.com/OpenRadioss/OpenRadioss/assets/105218709/cb9bbfca-441e-4cf1-ab4b-163fba5f6af2)
the increasing factor is about 3.33, there is still the losing of amplitude, but it does be improved.
the ratio thickness/mesh_size of this case is 8, and for your finest mesh case, the ratio is 16.

Regards

Qiang.

**Comment by Fonotec** [comment] 2023-08-16 16:06
Hi Qiang, 

I agree with what you are finding, this indeed reduces the decay in the amplitude also for me for this simulation. 

I performed a similar simulation such that the thickness is always smaller than the width of the shell elements and in this case I do not seem to get any decay. So I think that the main reason indeed is that the shell element becomes too thick. See the figure below, which is a cantiliver beam of 4000 mm x 1000 mm x 8 mm at different resolution. 

[cantileverbeamtest_100percent.pdf](https://github.com/OpenRadioss/OpenRadioss/files/12361324/cantileverbeamtest_100percent.pdf)

Overall, I think this implies that the shell should be thin enough for the standard OpenRadioss values to work. For me this is a satisfactory conclusion and for me the issue could be closed. 

Regards,
Folkert

**Comment by qiangRadioss** [comment] 2024-01-09 14:53
close the issue as mentioned Folkert in his last comment.

**Closed by qiangRadioss** 2024-01-09 14:53 UTC
